name: dermclass_structured
channels:
  - defaults
  - conda-forge
dependencies:
- pip
- setuptools
- wheel
- pyyaml
- scikit-learn
- numpy
- pandas
- scipy
- joblib
- pytest
- pytest-dependency
- pathlib
- fire
- optuna
- pip:
  - xgboost