name: dermclass2
channels:
  - defaults
  - conda-forge
dependencies:
- pip
- setuptools
- wheel
- scikit-learn
- numpy
- pandas
- scipy
- joblib
- pytest
- pytest-dependency
- pytest-ordering
- pathlib
- optuna
- pip:
  - xgboost