version: 2
jobs:
  test_dermclass_structured:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.9
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p miniconda
            source miniconda/etc/profile.d/conda.sh

            pip install --upgrade pip
            conda env create -f src/dermclass_structured/environment.yml
            conda activate dermclass_structured

            pytest -vv src/dermclass_structured/tests/tests.py
workflows:
  version: 2
  test-all:
    jobs:
      - test_dermclass_structured