# TODO: Remove redundant code
version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.9
  working_directory: ~/project

prepare_env: &prepare_env
  run:
    name: Prepare conda env
    command: |
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p miniconda
      pip install --upgrade pip

jobs:
  test_dermclass_structured:
    <<: *defaults
    steps:
      - checkout
      - *prepare_env
      - run:
          name: Create conda env and download packages
          command: |
            source miniconda/etc/profile.d/conda.sh
            conda env create -f src/dermclass_structured/environment.yml
      - run:
          name: Train model
          command: |
            source miniconda/etc/profile.d/conda.sh
            conda activate dermclass_structured
            PYTHONPATH=./src/dermclass_structured python src/dermclass_structured/dermclass_structured/train_pipeline.py --testing=True
      - run:
          name: Run tests
          command: |
            source miniconda/etc/profile.d/conda.sh
            conda activate dermclass_structured
            pytest -vv src/dermclass_structured/tests

  test_dermclass_api:
    <<: *defaults
    steps:
      - checkout
      - *prepare_env
      - run:
          name: Create conda env and download packages
          command: |
            source miniconda/etc/profile.d/conda.sh
            conda env create -f src/dermclass_api/environment.yml
      - run:
          name: Runnning tests
          command: |
            source miniconda/etc/profile.d/conda.sh
            conda activate dermclass_api
            pytest -vv src/dermclass_api/tests


  train_and_upload_structured_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_env
      - run:
          name: Create conda env and download packages
          command: |
            source miniconda/etc/profile.d/conda.sh
            conda env create -f src/dermclass_structured/environment.yml
      - run:
          name: Train model
          command: |
            source miniconda/etc/profile.d/conda.sh
            conda activate dermclass_structured
            PYTHONPATH=./src/dermclass_structured python src/dermclass_structured/dermclass_structured/train_pipeline.py
      - run:
          name: Publish model to Gemfury
          command: |
            chmod +x ./scripts/publish_model.sh
            ./scripts/publish_model.sh ./src/dermclass_structured/

workflows:
  version: 2
  test-all:
    jobs:
      - test_dermclass_structured
      #- test_dermclass_api
      - train_and_upload_structured_model:
          requires:
            - test_dermclass_structured
            #- test_dermclass_api
          # filters:
          #   branches:
          #     only:
          #       - master