name: dermclass_api
channels:
  - defaults
  - conda-forge
dependencies:
- pip
- setuptools
- wheel
- pyyaml
- flask
- flask-restful
- flask-marshmallow
- flask-sqlalchemy
- marshmallow-sqlalchemy
- pytest
- pillow
- pip:
    - gunicorn
    - dermclass_models