name: dermclass_api
channels:
  - defaults
  - conda-forge
dependencies:
- pip
- setuptools
- wheel
- flask
- flask_restful
- flask_marshmallow
- flas_sqlalchemy
- gunicorn
- pytest
#- pymongo
#- pip:
#    -