name: dermclass_api
channels:
  - defaults
  - conda-forge
dependencies:
- pip
- setuptools
- wheel
- flask
- flask-restful
- flask-marshmallow
- flask-sqlalchemy
- marshmallow-sqlalchemy
- pytest
- pytest-dependency
- pymongo
- scikit-learn
- numpy
- pandas
- scipy
- joblib
- pathlib
- seaborn
- optuna
- pip:
    - gunicorn
    - xgboost