name: dermclass_models
channels:
  - defaults
  - conda-forge
dependencies:
- pip
- setuptools
- wheel
- pyyaml
- pathlib
- joblib
- pytest
- pytest-sugar
- pytest-cov
- numpy
- pandas
- scipy
- scikit-learn
- optuna
- spacy
- spacy-model-en_core_web_sm
- tensorflow
- pip:
  - xgboost