name: dermclass_models
channels:
  - defaults
  - conda-forge
dependencies:
- pip
- setuptools
- wheel
- pyyaml
- pathlib
- joblib
- pytest
- pytest-sugar
- pytest-cov
- pytest-mock
- numpy
- pandas
- scipy
- scikit-learn
- optuna
- spacy
- pillow #?
#- spacy-model-en_core_web_sm
- transformers
- pip:
  - xgboost
  - tensorflow
  - opencv-python